version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  backend:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/database-name
    volumes:
      - ./server:/usr/src/app

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./client:/usr/src/app
